; PlatformIO Project Configuration File for Proxmox Server Monitor
;
; Build options: build flags, source filter
; Upload options: custom upload port, speed and extra flags
; Library options: dependencies, extra library storages

[env:uno]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 115200

lib_deps =
    adafruit/Adafruit GFX Library
    prenticedavid/MCUFRIEND_kbv
    adafruit/Adafruit TouchScreen
    adafruit/Adafruit BusIO
